create table if not exists public.project_heartbeat (
  id bigint generated by default as identity primary key,
  source text not null default 'scheduled-refresh',
  pinged_at timestamptz not null default now()
);

create index if not exists project_heartbeat_pinged_at_idx
  on public.project_heartbeat (pinged_at);

alter table public.project_heartbeat enable row level security;

-- The heartbeat is executed only by the server-side service role.
-- No anon or authenticated policy is required or intentionally exposed.
revoke all privileges on table public.project_heartbeat from anon, authenticated;

create or replace function public.refresh_project_activity()
returns timestamptz
language plpgsql
security definer
set search_path = public
as $$
declare
  heartbeat_time timestamptz;
begin
  insert into public.project_heartbeat (source)
  values ('scheduled-refresh')
  returning pinged_at into heartbeat_time;

  delete from public.project_heartbeat
  where pinged_at < now() - interval '30 days';

  return heartbeat_time;
end;
$$;

revoke all on function public.refresh_project_activity() from public;
revoke execute on function public.refresh_project_activity() from anon, authenticated;
grant execute on function public.refresh_project_activity() to service_role;

