import { createClient } from "@supabase/supabase-js";
import { Buffer } from "node:buffer";
import { NextResponse } from "next/server";
import { backupTableOptions, backupTables, getBackupTableLabel } from "@/lib/backupConfig";
import { createSupabaseServerClient } from "@/lib/supabaseServer";

function createServiceClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.");
  }

  assertServiceRoleKey(serviceRoleKey);

  return createClient(supabaseUrl, serviceRoleKey, {
    auth: {
      persistSession: false
    }
  });
}

function decodeBase64Url(value) {
  const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
  const padded = normalized.padEnd(normalized.length + ((4 - (normalized.length % 4)) % 4), "=");
  return Buffer.from(padded, "base64").toString("utf8");
}

function assertServiceRoleKey(key) {
  const parts = key.split(".");

  if (parts.length !== 3) {
    return;
  }

  try {
    const payload = JSON.parse(decodeBase64Url(parts[1]));

    if (payload.role !== "service_role") {
      throw new Error(
        "SUPABASE_SERVICE_ROLE_KEY is configured, but it is not a service_role key. Copy the service_role secret key from Supabase Project Settings > API Keys, then redeploy Vercel."
      );
    }
  } catch (error) {
    if (error.message?.includes("not a service_role key")) {
      throw error;
    }

    throw new Error("SUPABASE_SERVICE_ROLE_KEY could not be validated. Please re-copy the service_role key from Supabase.");
  }
}

function escapeCsv(value) {
  if (value === null || value === undefined) {
    return "";
  }

  const text = typeof value === "object" ? JSON.stringify(value) : String(value);
  return `"${text.replaceAll('"', '""')}"`;
}

function escapeXml(value) {
  if (value === null || value === undefined) {
    return "";
  }

  const text = typeof value === "object" ? JSON.stringify(value) : String(value);

  return text
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&apos;");
}

function resolveBackupFormat(value) {
  if (value === "csv") {
    return "csv";
  }

  if (value === "excel" || value === "xls") {
    return "excel";
  }

  return "json";
}

function backupToCsv(payload) {
  const lines = [
    "SISTECH DATABASE BACKUP",
    `Generated At,${escapeCsv(payload.meta.generated_at)}`,
    `Generated By,${escapeCsv(payload.meta.generated_by.full_name || payload.meta.generated_by.email || payload.meta.generated_by.id)}`,
    `Role,${escapeCsv(payload.meta.generated_by.role)}`,
    `Date Range Start,${escapeCsv(payload.meta.filters.start_at || "All")}`,
    `Date Range End,${escapeCsv(payload.meta.filters.end_at || "All")}`,
    `Selected Tables,${escapeCsv(payload.meta.selected_tables.map((table) => table.table).join(", "))}`,
    `Total Tables,${payload.meta.table_count}`,
    `Total Rows,${payload.meta.total_rows}`,
    "",
    "SUMMARY",
    "Table,Label,Rows"
  ];

  payload.summary.forEach((summary) => {
    lines.push([escapeCsv(summary.table), escapeCsv(summary.label), summary.row_count].join(","));
  });

  Object.entries(payload.tables).forEach(([tableName, tablePayload]) => {
    const records = tablePayload.records || [];
    const columns = tablePayload.columns || [];

    lines.push("");
    lines.push(`TABLE: ${tablePayload.label} (${tableName})`);
    lines.push(`Rows,${records.length}`);

    if (!records.length) {
      lines.push("No records");
      return;
    }

    lines.push(columns.map(escapeCsv).join(","));
    records.forEach((row) => {
      lines.push(columns.map((column) => escapeCsv(row?.[column])).join(","));
    });
  });

  return lines.join("\n");
}

function excelCell(value, style = "Cell", options = {}) {
  const isNumber = typeof value === "number" && Number.isFinite(value);
  const type = isNumber ? "Number" : "String";
  const attributes = [
    `ss:StyleID="${style}"`,
    options.mergeAcross ? `ss:MergeAcross="${options.mergeAcross}"` : ""
  ]
    .filter(Boolean)
    .join(" ");

  return `<Cell ${attributes}><Data ss:Type="${type}">${isNumber ? value : escapeXml(value)}</Data></Cell>`;
}

function excelRow(cells) {
  return `<Row>${cells.map((cell) => excelCell(cell.value, cell.style, cell)).join("")}</Row>`;
}

function excelColumns(widths) {
  return widths.map((width) => `<Column ss:AutoFitWidth="0" ss:Width="${width}"/>`).join("");
}

function getExcelColumnWidth(column) {
  const lower = column.toLowerCase();

  if (lower === "id" || lower.endsWith("_id")) {
    return 220;
  }

  if (lower.includes("description") || lower.includes("address") || lower.includes("message") || lower.includes("notes") || lower.includes("metadata")) {
    return 240;
  }

  if (lower.includes("date") || lower.includes("_at")) {
    return 140;
  }

  if (lower.includes("amount") || lower.includes("total") || lower.includes("value")) {
    return 120;
  }

  return 150;
}

function sanitizeWorksheetName(name, usedNames) {
  const cleaned = String(name || "Sheet")
    .replace(/[\\/?*:[\]]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, 31) || "Sheet";

  let sheetName = cleaned;
  let counter = 2;

  while (usedNames.has(sheetName)) {
    const suffix = ` ${counter}`;
    sheetName = `${cleaned.slice(0, 31 - suffix.length)}${suffix}`;
    counter += 1;
  }

  usedNames.add(sheetName);
  return sheetName;
}

function buildSummarySheet(payload, usedNames) {
  const rows = [
    excelRow([{ value: "SISTECH DATABASE BACKUP", style: "Title", mergeAcross: 3 }]),
    excelRow([{ value: "", style: "Cell" }]),
    excelRow([
      { value: "Generated At", style: "MetaLabel" },
      { value: payload.meta.generated_at, style: "MetaValue", mergeAcross: 2 }
    ]),
    excelRow([
      { value: "Generated By", style: "MetaLabel" },
      {
        value: payload.meta.generated_by.full_name || payload.meta.generated_by.email || payload.meta.generated_by.id,
        style: "MetaValue",
        mergeAcross: 2
      }
    ]),
    excelRow([
      { value: "Role", style: "MetaLabel" },
      { value: payload.meta.generated_by.role, style: "MetaValue", mergeAcross: 2 }
    ]),
    excelRow([
      { value: "Date Range Start", style: "MetaLabel" },
      { value: payload.meta.filters.start_at || "All", style: "MetaValue", mergeAcross: 2 }
    ]),
    excelRow([
      { value: "Date Range End", style: "MetaLabel" },
      { value: payload.meta.filters.end_at || "All", style: "MetaValue", mergeAcross: 2 }
    ]),
    excelRow([
      { value: "Total Tables", style: "MetaLabel" },
      { value: payload.meta.table_count, style: "MetaValue" }
    ]),
    excelRow([
      { value: "Total Rows", style: "MetaLabel" },
      { value: payload.meta.total_rows, style: "MetaValue" }
    ]),
    excelRow([{ value: "", style: "Cell" }]),
    excelRow([
      { value: "Table Label", style: "Header" },
      { value: "Database Table", style: "Header" },
      { value: "Group", style: "Header" },
      { value: "Rows", style: "Header" }
    ]),
    ...payload.summary.map((summary) => {
      const selectedTable = payload.meta.selected_tables.find((table) => table.table === summary.table);

      return excelRow([
        { value: summary.label, style: "Cell" },
        { value: summary.table, style: "Cell" },
        { value: selectedTable?.group || "-", style: "Cell" },
        { value: summary.row_count, style: "Number" }
      ]);
    })
  ];

  return `
    <Worksheet ss:Name="${escapeXml(sanitizeWorksheetName("Summary", usedNames))}">
      <Table>${excelColumns([220, 220, 160, 100])}${rows.join("")}</Table>
      <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
        <FreezePanes/>
        <FrozenNoSplit/>
        <SplitHorizontal>11</SplitHorizontal>
        <TopRowBottomPane>11</TopRowBottomPane>
        <ActivePane>2</ActivePane>
      </WorksheetOptions>
    </Worksheet>`;
}

function buildTableSheet(tableName, tablePayload, payload, usedNames) {
  const records = tablePayload.records || [];
  const columns = tablePayload.columns || [];
  const rows = [
    excelRow([{ value: tablePayload.label, style: "Title", mergeAcross: Math.max(columns.length - 1, 1) }]),
    excelRow([{ value: "", style: "Cell" }]),
    excelRow([
      { value: "Database Table", style: "MetaLabel" },
      { value: tableName, style: "MetaValue", mergeAcross: Math.max(columns.length - 2, 0) }
    ]),
    excelRow([
      { value: "Rows", style: "MetaLabel" },
      { value: records.length, style: "MetaValue" }
    ]),
    excelRow([
      { value: "Generated At", style: "MetaLabel" },
      { value: payload.meta.generated_at, style: "MetaValue", mergeAcross: Math.max(columns.length - 2, 0) }
    ]),
    excelRow([{ value: "", style: "Cell" }])
  ];

  if (!records.length) {
    rows.push(excelRow([{ value: "No records", style: "Empty", mergeAcross: Math.max(columns.length - 1, 1) }]));
  } else {
    rows.push(excelRow(columns.map((column) => ({ value: column, style: "Header" }))));

    records.forEach((record, index) => {
      const rowStyle = index % 2 === 0 ? "Cell" : "CellAlt";
      rows.push(
        excelRow(
          columns.map((column) => ({
            value: record?.[column],
            style: typeof record?.[column] === "number" ? "Number" : rowStyle
          }))
        )
      );
    });
  }

  const widths = columns.length ? columns.map(getExcelColumnWidth) : [220, 220];

  return `
    <Worksheet ss:Name="${escapeXml(sanitizeWorksheetName(tablePayload.label || tableName, usedNames))}">
      <Table>${excelColumns(widths)}${rows.join("")}</Table>
      <WorksheetOptions xmlns="urn:schemas-microsoft-com:office:excel">
        <FreezePanes/>
        <FrozenNoSplit/>
        <SplitHorizontal>7</SplitHorizontal>
        <TopRowBottomPane>7</TopRowBottomPane>
        <ActivePane>2</ActivePane>
      </WorksheetOptions>
    </Worksheet>`;
}

function backupToExcel(payload) {
  const usedNames = new Set();
  const sheets = [
    buildSummarySheet(payload, usedNames),
    ...Object.entries(payload.tables).map(([tableName, tablePayload]) =>
      buildTableSheet(tableName, tablePayload, payload, usedNames)
    )
  ];

  return `<?xml version="1.0" encoding="UTF-8"?>
<?mso-application progid="Excel.Sheet"?>
<Workbook
  xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <DocumentProperties xmlns="urn:schemas-microsoft-com:office:office">
    <Author>${escapeXml(payload.meta.generated_by.full_name || payload.meta.generated_by.email || "SISTECH")}</Author>
    <Created>${escapeXml(payload.meta.generated_at)}</Created>
    <Company>SISTECH</Company>
  </DocumentProperties>
  <Styles>
    <Style ss:ID="Default" ss:Name="Normal">
      <Alignment ss:Vertical="Top"/>
      <Font ss:FontName="Calibri" ss:Size="11" ss:Color="#334155"/>
    </Style>
    <Style ss:ID="Title">
      <Alignment ss:Vertical="Center"/>
      <Font ss:FontName="Calibri" ss:Size="16" ss:Bold="1" ss:Color="#0F172A"/>
      <Interior ss:Color="#E0F2FE" ss:Pattern="Solid"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="2" ss:Color="#0891B2"/>
      </Borders>
    </Style>
    <Style ss:ID="MetaLabel">
      <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#0F172A"/>
      <Interior ss:Color="#F8FAFC" ss:Pattern="Solid"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
      </Borders>
    </Style>
    <Style ss:ID="MetaValue">
      <Font ss:FontName="Calibri" ss:Size="11" ss:Color="#334155"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
      </Borders>
    </Style>
    <Style ss:ID="Header">
      <Alignment ss:Vertical="Center" ss:WrapText="1"/>
      <Font ss:FontName="Calibri" ss:Size="11" ss:Bold="1" ss:Color="#FFFFFF"/>
      <Interior ss:Color="#0F172A" ss:Pattern="Solid"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#94A3B8"/>
        <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#94A3B8"/>
        <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#94A3B8"/>
        <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#94A3B8"/>
      </Borders>
    </Style>
    <Style ss:ID="Cell">
      <Alignment ss:Vertical="Top" ss:WrapText="1"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
      </Borders>
    </Style>
    <Style ss:ID="CellAlt">
      <Alignment ss:Vertical="Top" ss:WrapText="1"/>
      <Interior ss:Color="#F8FAFC" ss:Pattern="Solid"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
      </Borders>
    </Style>
    <Style ss:ID="Number">
      <Alignment ss:Vertical="Top"/>
      <NumberFormat ss:Format="#,##0.00"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
      </Borders>
    </Style>
    <Style ss:ID="Empty">
      <Font ss:FontName="Calibri" ss:Size="11" ss:Italic="1" ss:Color="#64748B"/>
      <Interior ss:Color="#F8FAFC" ss:Pattern="Solid"/>
      <Borders>
        <Border ss:Position="Bottom" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Left" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Right" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
        <Border ss:Position="Top" ss:LineStyle="Continuous" ss:Weight="1" ss:Color="#CBD5E1"/>
      </Borders>
    </Style>
  </Styles>
  ${sheets.join("")}
</Workbook>`;
}

function parseDateParam(value, label) {
  if (!value) {
    return null;
  }

  const parsed = new Date(value);

  if (Number.isNaN(parsed.getTime())) {
    throw new Error(`${label} is not a valid date/time.`);
  }

  return parsed.toISOString();
}

function resolveRequestedTables(searchParams) {
  const requestedTables = searchParams.get("tables");

  if (!requestedTables || requestedTables === "all") {
    return backupTables;
  }

  const selectedTables = requestedTables
    .split(",")
    .map((table) => table.trim())
    .filter(Boolean);
  const allowedTables = new Set(backupTables);
  const invalidTables = selectedTables.filter((table) => !allowedTables.has(table));

  if (invalidTables.length) {
    throw new Error(`Invalid backup table selected: ${invalidTables.join(", ")}.`);
  }

  if (!selectedTables.length) {
    throw new Error("Select at least one database table to backup.");
  }

  return Array.from(new Set(selectedTables));
}

export async function GET(request) {
  const format = resolveBackupFormat(request.nextUrl.searchParams.get("format"));
  const requestedAt = new Date().toISOString();

  try {
    const startAt = parseDateParam(request.nextUrl.searchParams.get("start_at"), "Start date/time");
    const endAt = parseDateParam(request.nextUrl.searchParams.get("end_at"), "End date/time");

    if (startAt && endAt && new Date(startAt) > new Date(endAt)) {
      return NextResponse.json({ error: "Start date/time must be before end date/time." }, { status: 400 });
    }

    let selectedTables;

    try {
      selectedTables = resolveRequestedTables(request.nextUrl.searchParams);
    } catch (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    const sessionClient = await createSupabaseServerClient();
    const { data: userData, error: userError } = await sessionClient.auth.getUser();
    const user = userData?.user;

    if (userError || !user) {
      return NextResponse.json({ error: "Unauthorized. Please login as admin." }, { status: 401 });
    }

    const { data: profile, error: profileError } = await sessionClient
      .from("profiles")
      .select("id, email, full_name, role")
      .eq("id", user.id)
      .single();

    if (profileError || profile?.role !== "admin") {
      return NextResponse.json({ error: "Forbidden. Admin role is required for database backup." }, { status: 403 });
    }

    const serviceClient = createServiceClient();
    const tables = {};
    const summary = [];

    for (const tableName of selectedTables) {
      let query = serviceClient
        .from(tableName)
        .select("*")
        .limit(50000);

      if (startAt) {
        query = query.gte("created_at", startAt);
      }

      if (endAt) {
        query = query.lte("created_at", endAt);
      }

      const { data, error } = await query;

      if (error) {
        throw new Error(`Backup failed while reading ${tableName}: ${error.message}`);
      }

      const records = data || [];
      const columns = Array.from(new Set(records.flatMap((row) => Object.keys(row || {}))));
      const tableSummary = {
        table: tableName,
        label: getBackupTableLabel(tableName),
        row_count: records.length
      };

      summary.push(tableSummary);
      tables[tableName] = {
        ...tableSummary,
        columns,
        records
      };
    }

    const totalRows = summary.reduce((total, table) => total + table.row_count, 0);

    const { error: auditError } = await serviceClient.from("audit_logs").insert({
      user_id: user.id,
      action: "backup_database",
      module: "Administration",
      table_name: "database_backup",
      metadata: {
        format,
        requested_at: requestedAt,
        start_at: startAt,
        end_at: endAt,
        tables: selectedTables,
        table_count: selectedTables.length,
        total_rows: totalRows
      }
    });

    if (auditError) {
      throw new Error(`Backup audit log failed: ${auditError.message}`);
    }

    const payload = {
      meta: {
        app: "SISTECH",
        generated_at: requestedAt,
        generated_by: {
          id: profile.id,
          email: profile.email,
          full_name: profile.full_name,
          role: profile.role
        },
        table_count: selectedTables.length,
        total_rows: totalRows,
        selected_tables: selectedTables.map((tableName) => ({
          table: tableName,
          label: getBackupTableLabel(tableName),
          group: backupTableOptions.find((table) => table.value === tableName)?.group || "Other"
        })),
        filters: {
          start_at: startAt,
          end_at: endAt
        }
      },
      summary,
      tables
    };

    const safeTimestamp = requestedAt.replace(/[:.]/g, "-");
    const scopeName = selectedTables.length === backupTables.length ? "all" : "selected";

    if (format === "csv") {
      return new Response(backupToCsv(payload), {
        headers: {
          "content-type": "text/csv; charset=utf-8",
          "content-disposition": `attachment; filename="sistech-backup-${scopeName}-${safeTimestamp}.csv"`
        }
      });
    }

    if (format === "excel") {
      return new Response(backupToExcel(payload), {
        headers: {
          "content-type": "application/vnd.ms-excel; charset=utf-8",
          "content-disposition": `attachment; filename="sistech-backup-${scopeName}-${safeTimestamp}.xls"`
        }
      });
    }

    return new Response(JSON.stringify(payload, null, 2), {
      headers: {
        "content-type": "application/json; charset=utf-8",
        "content-disposition": `attachment; filename="sistech-backup-${scopeName}-${safeTimestamp}.json"`
      }
    });
  } catch (error) {
    return NextResponse.json({ error: error.message || "Backup failed." }, { status: 500 });
  }
}
