import { createClient } from "@supabase/supabase-js";
import { Buffer } from "node:buffer";
import { NextResponse } from "next/server";
import { backupTableOptions, backupTables, getBackupTableLabel } from "@/lib/backupConfig";
import { createSupabaseServerClient } from "@/lib/supabaseServer";

function createServiceClient() {
  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceRoleKey = process.env.SUPABASE_SERVICE_ROLE_KEY;

  if (!supabaseUrl || !serviceRoleKey) {
    throw new Error("Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY.");
  }

  assertServiceRoleKey(serviceRoleKey);

  return createClient(supabaseUrl, serviceRoleKey, {
    auth: {
      persistSession: false
    }
  });
}

function decodeBase64Url(value) {
  const normalized = value.replace(/-/g, "+").replace(/_/g, "/");
  const padded = normalized.padEnd(normalized.length + ((4 - (normalized.length % 4)) % 4), "=");
  return Buffer.from(padded, "base64").toString("utf8");
}

function assertServiceRoleKey(key) {
  const parts = key.split(".");

  if (parts.length !== 3) {
    return;
  }

  try {
    const payload = JSON.parse(decodeBase64Url(parts[1]));

    if (payload.role !== "service_role") {
      throw new Error(
        "SUPABASE_SERVICE_ROLE_KEY is configured, but it is not a service_role key. Copy the service_role secret key from Supabase Project Settings > API Keys, then redeploy Vercel."
      );
    }
  } catch (error) {
    if (error.message?.includes("not a service_role key")) {
      throw error;
    }

    throw new Error("SUPABASE_SERVICE_ROLE_KEY could not be validated. Please re-copy the service_role key from Supabase.");
  }
}

function escapeCsv(value) {
  if (value === null || value === undefined) {
    return "";
  }

  const text = typeof value === "object" ? JSON.stringify(value) : String(value);
  return `"${text.replaceAll('"', '""')}"`;
}

function backupToCsv(payload) {
  const lines = [
    "SISTECH DATABASE BACKUP",
    `Generated At,${escapeCsv(payload.meta.generated_at)}`,
    `Generated By,${escapeCsv(payload.meta.generated_by.full_name || payload.meta.generated_by.email || payload.meta.generated_by.id)}`,
    `Role,${escapeCsv(payload.meta.generated_by.role)}`,
    `Date Range Start,${escapeCsv(payload.meta.filters.start_at || "All")}`,
    `Date Range End,${escapeCsv(payload.meta.filters.end_at || "All")}`,
    `Selected Tables,${escapeCsv(payload.meta.selected_tables.map((table) => table.table).join(", "))}`,
    `Total Tables,${payload.meta.table_count}`,
    `Total Rows,${payload.meta.total_rows}`,
    "",
    "SUMMARY",
    "Table,Label,Rows"
  ];

  payload.summary.forEach((summary) => {
    lines.push([escapeCsv(summary.table), escapeCsv(summary.label), summary.row_count].join(","));
  });

  Object.entries(payload.tables).forEach(([tableName, tablePayload]) => {
    const records = tablePayload.records || [];
    const columns = tablePayload.columns || [];

    lines.push("");
    lines.push(`TABLE: ${tablePayload.label} (${tableName})`);
    lines.push(`Rows,${records.length}`);

    if (!records.length) {
      lines.push("No records");
      return;
    }

    lines.push(columns.map(escapeCsv).join(","));
    records.forEach((row) => {
      lines.push(columns.map((column) => escapeCsv(row?.[column])).join(","));
    });
  });

  return lines.join("\n");
}

function parseDateParam(value, label) {
  if (!value) {
    return null;
  }

  const parsed = new Date(value);

  if (Number.isNaN(parsed.getTime())) {
    throw new Error(`${label} is not a valid date/time.`);
  }

  return parsed.toISOString();
}

function resolveRequestedTables(searchParams) {
  const requestedTables = searchParams.get("tables");

  if (!requestedTables || requestedTables === "all") {
    return backupTables;
  }

  const selectedTables = requestedTables
    .split(",")
    .map((table) => table.trim())
    .filter(Boolean);
  const allowedTables = new Set(backupTables);
  const invalidTables = selectedTables.filter((table) => !allowedTables.has(table));

  if (invalidTables.length) {
    throw new Error(`Invalid backup table selected: ${invalidTables.join(", ")}.`);
  }

  if (!selectedTables.length) {
    throw new Error("Select at least one database table to backup.");
  }

  return Array.from(new Set(selectedTables));
}

export async function GET(request) {
  const format = request.nextUrl.searchParams.get("format") === "csv" ? "csv" : "json";
  const requestedAt = new Date().toISOString();

  try {
    const startAt = parseDateParam(request.nextUrl.searchParams.get("start_at"), "Start date/time");
    const endAt = parseDateParam(request.nextUrl.searchParams.get("end_at"), "End date/time");

    if (startAt && endAt && new Date(startAt) > new Date(endAt)) {
      return NextResponse.json({ error: "Start date/time must be before end date/time." }, { status: 400 });
    }

    let selectedTables;

    try {
      selectedTables = resolveRequestedTables(request.nextUrl.searchParams);
    } catch (error) {
      return NextResponse.json({ error: error.message }, { status: 400 });
    }

    const sessionClient = await createSupabaseServerClient();
    const { data: userData, error: userError } = await sessionClient.auth.getUser();
    const user = userData?.user;

    if (userError || !user) {
      return NextResponse.json({ error: "Unauthorized. Please login as admin." }, { status: 401 });
    }

    const { data: profile, error: profileError } = await sessionClient
      .from("profiles")
      .select("id, email, full_name, role")
      .eq("id", user.id)
      .single();

    if (profileError || profile?.role !== "admin") {
      return NextResponse.json({ error: "Forbidden. Admin role is required for database backup." }, { status: 403 });
    }

    const serviceClient = createServiceClient();
    const tables = {};
    const summary = [];

    for (const tableName of selectedTables) {
      let query = serviceClient
        .from(tableName)
        .select("*")
        .limit(50000);

      if (startAt) {
        query = query.gte("created_at", startAt);
      }

      if (endAt) {
        query = query.lte("created_at", endAt);
      }

      const { data, error } = await query;

      if (error) {
        throw new Error(`Backup failed while reading ${tableName}: ${error.message}`);
      }

      const records = data || [];
      const columns = Array.from(new Set(records.flatMap((row) => Object.keys(row || {}))));
      const tableSummary = {
        table: tableName,
        label: getBackupTableLabel(tableName),
        row_count: records.length
      };

      summary.push(tableSummary);
      tables[tableName] = {
        ...tableSummary,
        columns,
        records
      };
    }

    const totalRows = summary.reduce((total, table) => total + table.row_count, 0);

    const { error: auditError } = await serviceClient.from("audit_logs").insert({
      user_id: user.id,
      action: "backup_database",
      module: "Administration",
      table_name: "database_backup",
      metadata: {
        format,
        requested_at: requestedAt,
        start_at: startAt,
        end_at: endAt,
        tables: selectedTables,
        table_count: selectedTables.length,
        total_rows: totalRows
      }
    });

    if (auditError) {
      throw new Error(`Backup audit log failed: ${auditError.message}`);
    }

    const payload = {
      meta: {
        app: "SISTECH",
        generated_at: requestedAt,
        generated_by: {
          id: profile.id,
          email: profile.email,
          full_name: profile.full_name,
          role: profile.role
        },
        table_count: selectedTables.length,
        total_rows: totalRows,
        selected_tables: selectedTables.map((tableName) => ({
          table: tableName,
          label: getBackupTableLabel(tableName),
          group: backupTableOptions.find((table) => table.value === tableName)?.group || "Other"
        })),
        filters: {
          start_at: startAt,
          end_at: endAt
        }
      },
      summary,
      tables
    };

    const safeTimestamp = requestedAt.replace(/[:.]/g, "-");
    const scopeName = selectedTables.length === backupTables.length ? "all" : "selected";

    if (format === "csv") {
      return new Response(backupToCsv(payload), {
        headers: {
          "content-type": "text/csv; charset=utf-8",
          "content-disposition": `attachment; filename="sistech-backup-${scopeName}-${safeTimestamp}.csv"`
        }
      });
    }

    return new Response(JSON.stringify(payload, null, 2), {
      headers: {
        "content-type": "application/json; charset=utf-8",
        "content-disposition": `attachment; filename="sistech-backup-${scopeName}-${safeTimestamp}.json"`
      }
    });
  } catch (error) {
    return NextResponse.json({ error: error.message || "Backup failed." }, { status: 500 });
  }
}
